### ISSUE TITLE
Options for SPA

### ISSUE THREAD

**Issue by niallobrien** [jfelsinger/generator-venm#1]
Hi, nice work - would be good if you clarified that this scaffolds a server-side application, as opposed to the MEAN stack which focuses on scaffolding a client-side application and a backend API.
Perhaps even add in the option for this and then pull in a router and build process for client-side apps.

**Comment by jfelsinger** [comment]
Thanks for the feedback. I'm currently working on changing up a lot of things with this generator, especially in the ways of improving the scaffolding for both ends. (It's a bit dated at the moment.) When I do, I'll be sure to also update the documentation to make things more clear.

I'll especially be sure to give some love for SPAs.

**Comment by niallobrien** [comment]
Sounds great, thanks.

**Comment by niallobrien** [comment]
Would you accept PRs to update package versions and ensure they're all working?

**Comment by jfelsinger** [comment]
I absolutely would. Unfortunately I haven't had the time to maintain this
much, but I'd be glad to accept any contributions. They'd be much
appreciated.

**Comment by niallobrien** [comment]
What's the status on this or would you rather people fork it?

**Comment by niallobrien** [comment]
Closing as I assume that this project has been abandoned. :(
